IDENTIFICATION DIVISION.
PROGRAM-ID. ADD-NUMBERS.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 NUM1          PIC 9(5) VALUE 0.
01 NUM2          PIC 9(5) VALUE 0.
01 SUM           PIC 9(6) VALUE 0.

PROCEDURE DIVISION.
    DISPLAY "Enter the first number: ".
    ACCEPT NUM1.

    DISPLAY "Enter the second number: ".
    ACCEPT NUM2.

    COMPUTE SUM = NUM1 + NUM2.

    DISPLAY "The sum of " NUM1 " and " NUM2 " is " SUM.

    STOP RUN.
