name: code_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.2
  graphview: ^1.2.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  dio: ^5.7.0
  file_picker: ^8.1.5
  shared_preferences: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
